#!/usr/bin/env bash
#install load balancer

sudo apt-get -y upgrade
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.default
echo "listen appname
        bind *:80
        mode http
        balance roundrobin
        server 956-web-01 35.229.86.70:80 check
        server 956-web-02 35.237.216.255:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
