#!/usr/bin/env bash
# loops from 1 to 10 and displays
# "bad luck" for the 4th loop iteration
# "good luck" for the 8th loop iteration
# "Holberton School" for the other iterations

COUNTER=0

while (( COUNTER < 10 ))
do
    if [ "$COUNTER" -eq "3" ]
    then
	echo "bad luck"
    elif [ "$COUNTER" -eq "7" ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    (( COUNTER++ ))
done
